apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-no-dockerfile-wy7o
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-no-dockerfile-wy7o
    app.kubernetes.io/part-of: test-app-xfba
  name: nodejs-no-dockerfile-wy7owema
spec:
  path: /
  port:
    targetPort: 8080
  to:
    kind: Service
    name: nodejs-no-dockerfile-wy7o
    weight: null
status: {}
