apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: maven-hello-world-ktuu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: maven-hello-world-ktuu
    app.kubernetes.io/part-of: test-app-xfba
  name: maven-hello-world-ktuu
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: maven-hello-world-ktuu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: maven-hello-world-ktuu
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-rvbb-tenant/test-app-xfba/maven-hello-world-ktuu@sha256:e8f82fdfa4e9271016be9e8869310877c28208bfa4444b33eff3a13a6275ff79
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
