apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: maven-hello-world-ktuu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: maven-hello-world-ktuu
    app.kubernetes.io/part-of: test-app-xfba
  name: maven-hello-world-ktuu
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: java-quarkus-app
    app.kubernetes.io/instance: maven-hello-world-ktuu
status:
  loadBalancer: {}
